#!/bin/bash

echo "Dont run the script now !"

exit

####
#options
####
echo "Setup wireguard"
echo
read -p "Set the Server ipv4 (endpoint) :  " -e -i ServerIP IP01
read -p "Set the Wireguard Server Port :  " -e -i 54321 wg0port
read -p "Set the Servers PuplicKey :  " -e -i ServerPupKey PK04
read -p "Set client ipv4 without /32 :  " -e -i 10.8.0.2 cipv4
read -p "Set client ipv6 without /128 :  " -e -i fd42:42:42:42::2 cipv6
read -p "Set client DNS ipv4 :  " -e -i 10.8.0.1 DNSv4
read -p "Set client DNS ipv6 :  " -e -i fd42:42:42:42::1 DNSv6
echo
echo
echo "###########################################"
echo
echo
echo "Setup your WiFi"
echo
read -p "WiFi SSID  :  " -e -i Wlanname ssid
read -p "WiFi Password :  " -e -i password ssidpasswd
echo
echo


####
#stuff
####
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install raspberrypi-kernel-headers -y
echo "deb http://deb.debian.org/debian/ unstable main" | sudo tee --append /etc/apt/sources.list.d/unstable.list
sudo apt-get install dirmngr -y
sudo apt-key adv --keyserver   keyserver.ubuntu.com --recv-keys 8B48AD6246925553 
printf 'Package: *\nPin: release a=unstable\nPin-Priority: 150\n' | sudo tee --append /etc/apt/preferences.d/limit-unstable
sudo apt-get update
sudo apt-get install wireguard dnsmasq -y





####
#network
####

sudo mv /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf.orig
echo "
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
    ssid=""$ssid""
    psk=""$ssidpasswd""
    }" | sudo tee --append /etc/wpa_supplicant/wpa_supplicant.conf > /dev/null



sudo cp /etc/sysctl.conf /etc/sysctl.conf.orig
sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
sudo sed -i 's/#net.ipv6.conf.all.forwarding=1/net.ipv6.conf.all.forwarding=1/g' /etc/sysctl.conf
echo "net.ipv6.conf.all.autoconf=0
net.ipv6.conf.eth0.autoconf=0" | sudo tee --append /etc/sysctl.conf > /dev/null


sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
sudo iptables -A FORWARD -i wg0 -o wg0 -m conntrack --ctstate NEW -j ACCEPT


sudo mv /etc/dhcpcd.conf /etc/dhcpcd.conf.orig
echo "
wireguardpi
clientid
persistent
option rapid_commit
option classless_static_routes
option ntp_servers
option interface_mtu
require dhcp_server_identifier
slaac private

interface eth0
static ip_address=10.7.0.1/24
static ip6_address=fd00:10:7:0::1/64
static routers=10.7.0.1
static domain_name_servers=$DNSv4 $DNSv6" | sudo tee --append /etc/dhcpcd.conf > /dev/null


sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig

echo "interface=eth0
no-dhcp-interface=wlan0
dhcp-range=fd00:10:7:0::2,fd00:10:7:0::52,24h
dhcp-range=10.7.0.2,10.7.0.52,24h" | sudo tee --append /etc/dnsmasq.conf > /dev/null


####
#wireguard
####

sudo mkdir /etc/wireguard/keys
sudo chmod 700 /etc/wireguard/keys
sudo touch /etc/wireguard/keys/clientpi
sudo chmod 600 /etc/wireguard/keys/clientpi
sudo wg genkey > /etc/wireguard/keys/clientpi
sudo wg pubkey < /etc/wireguard/keys/clientpi > /etc/wireguard/keys/clientpi.pub

echo "[Interface]
Address = $cipv4/32
Address = $cipv6/128
PrivateKey = PK03
DNS = $DNSv4, DNSv6

[Peer]
Endpoint = $IP01:$wg0port
PublicKey = $PK04
AllowedIPs = 0.0.0.0/0, ::/0
" | sudo tee --append /etc/wireguard/clientpi.conf > /dev/null
sudo sed -i "s@PK03@$(cat /etc/wireguard/keys/clientpi)@" /etc/wireguard/clientpi.conf
chmod 600 /etc/wireguard/clientpi.conf

echo
echo
echo "########################################################################"
echo
pupkey=$(cat /etc/wireguard/keys/clientpi.pub)
echo "Set your client data in to your wireguard server config :"
echo
echo "[Peer]
PublicKey = $pupkey
AllowedIPs = $cipv4/32, $cipv6/128"
echo
echo "########################################################################"
echo
echo
echo


####
#finish
####
sudo systemctl enable wg-quick@clientpi.service
sudo systemctl start wg-quick@clientpi.service
sudo systemctl restart dnsmasq
sudo systemctl enable dnsmasq
sudo service networking restart
