#!/bin/bash

####
#options
####
echo "Setup wireguard"
echo
read -p "Set the Server ipv4 (endpoint) :  " -e -i ServerIP IP01
read -p "Set the Wireguard Server Port :  " -e -i 54321 wg0port
read -p "Set the Servers PuplicKey :  " -e -i ServerPupKey PK04
read -p "Set client ipv4 without /32 :  " -e -i 10.8.0.3 cipv4
read -p "Set client ipv6 without /128 :  " -e -i fd42:42:42:42::3 cipv6
read -p "Set client DNS ipv4 :  " -e -i 10.8.0.1 DNSv4
read -p "Set client DNS ipv6 :  " -e -i fd42:42:42:42::1 DNSv6
echo
echo
echo "###########################################"
echo
echo
echo "Setup your WiFi"
echo
read -p "WiFi SSID  :  " -e -i Wlanname ssid
read -p "WiFi Password  :  " -e -i password ssidpasswd
echo
echo

####
#stuff
####
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install raspberrypi-kernel-headers -y
echo "deb http://deb.debian.org/debian/ unstable main" | sudo tee --append /etc/apt/sources.list.d/unstable.list
sudo apt-get install dirmngr -y
sudo apt-key adv --keyserver   keyserver.ubuntu.com --recv-keys 8B48AD6246925553 
printf 'Package: *\nPin: release a=unstable\nPin-Priority: 150\n' | sudo tee --append /etc/apt/preferences.d/limit-unstable
sudo apt-get update
sudo apt-get install wireguard isc-dhcp-server -y


####
#network 
####
echo '
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
    ssid="'"${ssid}"'"
    psk="'"${ssidpasswd}"'"
    }' | sudo tee --append /etc/wpa_supplicant/wpa_supplicant.conf > /dev/null


sudo cp /etc/sysctl.conf /etc/sysctl.conf.orig
sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
sudo sed -i 's/#net.ipv6.conf.all.forwarding=1/net.ipv6.conf.all.forwarding=1/g' /etc/sysctl.conf
echo "net.ipv6.conf.all.autoconf=0
net.ipv6.conf.eth0.autoconf=0" | sudo tee --append /etc/sysctl.conf > /dev/null


sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
sudo iptables -A FORWARD -i wg0 -o wg0 -m conntrack --ctstate NEW -j ACCEPT
sudo ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo ip6tables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
sudo ip6tables -A FORWARD -i wg0 -o wg0 -m conntrack --ctstate NEW -j ACCEPT
sudo bash -c "iptables-save > /etc/iptables.rules"
sudo bash -c "ip6tables-save > /etc/ip6tables.rules"

sudo mv /etc/default/isc-dhcp-server /etc/default/isc-dhcp-server.orig
echo 'INTERFACESv4="eth0"' | sudo tee --append /etc/default/isc-dhcp-server > /dev/null
sudo mv /etc/default/isc-dhcp-server /etc/default/isc-dhcp-server6
echo 'INTERFACESv6="eth0"' | sudo tee --append /etc/default/isc-dhcp-server6 > /dev/null


sudo mv  /etc/dhcpcd.conf.orig
echo "
authoritative;
default-lease-time 86400;
max-lease-time 86400;
slaac private;

interface eth0
static ip_address=10.7.0.1/24
static ip6_address=fd00:10:7:0::1/64
static routers=10.7.0.1
#static routers=$DNSv4
static domain_name_servers=$DNSv4 $DNSv6
" | sudo tee --append /etc/dhcpcd.conf > /dev/null


sudo mv /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.orig
echo "subnet 10.7.0.0 netmask 255.255.255.0 {
  range 10.7.0.2 10.7.0.52;
  option routers 10.7.0.1;
  option domain-name-servers 10.7.0.1;
  option domain-name "local";
}" | sudo tee --append /etc/dhcp/dhcpd.conf > /dev/null


sudo mv /etc/dhcp/dhcpd6.conf /etc/dhcp/dhcpd6.conf.orig
echo "subnet6 fd00:10:7:0::/64 {
        range6 fd00:10:7:0::2 fd00:10:7:0::52;
        option dhcp6.name-servers fd00:10:7:0::1;
        option dhcp6.domain-search "local";
}" | sudo tee --append /etc/dhcp/dhcpd6.conf > /dev/null


####
#wireguard
####

sudo mkdir /etc/wireguard/keys
sudo chmod 700 /etc/wireguard/keys
sudo touch /etc/wireguard/keys/wg0
sudo chmod 600 /etc/wireguard/keys/wg0
sudo wg genkey > /etc/wireguard/keys/wg0
sudo wg pubkey < /etc/wireguard/keys/wg0 > /etc/wireguard/keys/wg0.pub

echo "[Interface]
Address = $cipv4/32
Address = $cipv6/128
PrivateKey = PK03
DNS = $DNSv4, DNSv6

[Peer]
Endpoint = $IP01:$wg0port
PublicKey = $PK04
AllowedIPs = 0.0.0.0/0, ::/0
" | sudo tee --append /etc/wireguard/wg0.conf > /dev/null
sudo sed -i "s@PK03@$(cat /etc/wireguard/keys/wg0)@" /etc/wireguard/wg0.conf
chmod 600 /etc/wireguard/wg0.conf

echo
echo
echo "########################################################################"
echo
pupkey=$(cat /etc/wireguard/keys/wg0.pub)
echo "Set your client data in to your wireguard server config :"
echo
echo "[Peer]
PublicKey = $pupkey
AllowedIPs = $cipv4/32, $cipv6/128"
echo
echo "########################################################################"
echo
echo
echo


####
#finish
####
sudo systemctl enable wg-quick@wg0.service
sudo systemctl start wg-quick@wg0.service
sudo systemctl restart isc-dhcp-server
sudo systemctl restart isc-dhcp-server6
sudo systemctl enable isc-dhcp-server
sudo systemctl enable isc-dhcp-server6
sudo service networking restart
